# Generated by Django 4.2.2 on 2023-09-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0023_rename_faculty_myuploadedfiles_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFiles',
        ),
    ]
