# Generated by Django 4.2.2 on 2023-09-23 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Intern_Portal', '0026_remove_myuploadedfiles_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadedfiles',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
