# Generated by Django 4.2.2 on 2023-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0028_remove_faculty_profile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuploadedfiles',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
    ]
