# Generated by Django 4.2.2 on 2023-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0029_myuploadedfiles_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuploadedfiles',
            old_name='marks',
            new_name='marks1',
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
