# Generated by Django 4.2.2 on 2023-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0030_rename_marks_myuploadedfiles_marks1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadedfiles',
            name='average_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks7',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='marks8',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
