# Generated by Django 4.2.1 on 2023-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0031_myuploadedfiles_average_marks_myuploadedfiles_marks4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod_profile',
            name='username',
        ),
        migrations.AddField(
            model_name='hod_profile',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
