# Generated by Django 4.2.2 on 2024-01-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0033_privatefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefile',
            name='student_mapping',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Intern_Portal.studentfacultymapping'),
            preserve_default=False,
        ),
    ]
