# Generated by Django 4.2.2 on 2024-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0034_privatefile_student_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_dates', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('eligibility_criteria', models.TextField()),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
