# Generated by Django 4.2.2 on 2024-02-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0036_document_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
