# Generated by Django 4.2.2 on 2024-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0037_remove_domain_documents_remove_domain_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('Web Development', 'Web Development'), ('AIML', 'AIML')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
